# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: backend
    command: >
      bash entrypoint.sh
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: hello_dev
      PGPORT: 5432
      PGHOSTNAME: db
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build:
      # Here we define that it should build from the current directory
      context: frontend
    environment:
      # Variables to connect to our Postgres server
      VUE_APP_URL: http://localhost:4000
    ports:
      - 8080:80
    depends_on:
      - phoenix
# Define the volumes
volumes:
  pgdata: